Scripts recursively display error lines

diff --git a/src/core/scripts/gino b/src/core/scripts/gino
--- a/src/core/scripts/gino
+++ b/src/core/scripts/gino
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
 if test $# -lt 3 ; then
   echo "USAGE: `basename $0` INPUT_BITCODE -o OUTPUT_BITCODE"
@@ -9,46 +9,30 @@ fi
 
 inputIR=$1
 afterLoopMetadata="afterLoopMetadata.bc"
-intermediateResult="baseline_with_parallel_plan.bc" ;
-intermediateResult_unoptimized="parallelized_unoptimized.bc" ;
+intermediateResult="baseline_with_parallel_plan.bc"
+intermediateResult_unoptimized="parallelized_unoptimized.bc"
 outputIR=$3
 
-# Step 0: Add loop ID to all loops
-cmdToExecute="noelle-meta-loop-embed ${inputIR} -o ${afterLoopMetadata}"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# step 0: add loop id to all loops
+noelle-meta-loop-embed ${inputIR} -o ${afterLoopMetadata}
 
-# Step 1: Run parallelization planner
-cmdToExecute="gino-planner ${afterLoopMetadata} -o ${intermediateResult} ${@:4}" ;
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# step 1: run parallelization planner
+gino-planner ${afterLoopMetadata} -o ${intermediateResult} ${@:4}
 
-# Step 2: Include function prototypes needed by parallelization techniques
-clang -c -emit-llvm NOELLE_APIs.c ;
-llvm-link NOELLE_APIs.bc ${intermediateResult} -o code_with_prototypes.bc ;
-cmdToExecute="noelle-rm-function -function-name=SIMONE_CAMPANONI_IS_GOING_TO_REMOVE_THIS_FUNCTION code_with_prototypes.bc -o code_to_parallelize.bc" ;
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# step 2: include function prototypes needed by parallelization techniques
+clang -c -emit-llvm NOELLE_APIs.c
+llvm-link NOELLE_APIs.bc ${intermediateResult} -o code_with_prototypes.bc
+noelle-rm-function -function-name=SIMONE_CAMPANONI_IS_GOING_TO_REMOVE_THIS_FUNCTION code_with_prototypes.bc -o code_to_parallelize.bc
 
-# Step 3: Run loop parallelization on bitcode with parallel plan
-cmdToExecute="gino-loops code_to_parallelize.bc -o ${intermediateResult_unoptimized} ${@:4}" ;
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# step 3: run loop parallelization on bitcode with parallel plan
+gino-loops code_to_parallelize.bc -o ${intermediateResult_unoptimized} ${@:4}
 
-# Step 4: cleaning the metadata that are now disaligned with the code
-cmdToExecute="noelle-meta-clean ${intermediateResult_unoptimized} -o ${intermediateResult_unoptimized}" ;
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# step 4: cleaning the metadata that are now disaligned with the code
+noelle-meta-clean ${intermediateResult_unoptimized} -o ${intermediateResult_unoptimized}
+clang -O3 -c -emit-llvm ${intermediateResult_unoptimized} -o ${outputIR}
 
-# Step 5: conventional optimizations
-cmdToExecute="clang -O3 -c -emit-llvm ${intermediateResult_unoptimized} -o ${outputIR}" ;
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# step 6: link with the runtime
+llvm-link ${outputIR} Parallelizer_utils.bc -o ${outputIR}
 
-# Step 6: Link with the runtime
-llvm-link ${outputIR} Parallelizer_utils.bc -o ${outputIR} ;
-
-# Step 7: conventional optimizations
-cmdToExecute="clang -O3 -c -emit-llvm ${outputIR} -o ${outputIR}" ;
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# step 7: conventional optimizations
+clang -O3 -c -emit-llvm ${outputIR} -o ${outputIR}
diff --git a/src/core/scripts/gino-enable b/src/core/scripts/gino-enable
--- a/src/core/scripts/gino-enable
+++ b/src/core/scripts/gino-enable
@@ -1,13 +1,7 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
-# Fetch the install directory of NOELLE
-noelleInstallDir="`noelle-config --prefix`" ;
-
-# Run the enablers until a fixed point is reached
-echo "GINO: Enablers: Start" ;
-cmdToExecute="noelle-fixedpoint $1 $2 \"gino-load\" -enablers ${@:3}"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
-echo "GINO: Enablers: Exit" ;
+echo "GINO: Enablers: Start"
+noelle-fixedpoint $1 $2 "gino-load" -enablers ${@:3}
+echo "GINO: Enablers: Exit"
diff --git a/src/core/scripts/gino-inline b/src/core/scripts/gino-inline
--- a/src/core/scripts/gino-inline
+++ b/src/core/scripts/gino-inline
@@ -1,10 +1,8 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
-# Delete dead functions until a fixed point is reached
-echo "GINO: Inliner: Start" ;
-cmdToExecute="noelle-fixedpoint $1 $1 \"gino-load\" -inliner ${@:2}"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
-echo "GINO: Inliner: Exit" ;
+# delete dead functions until a fixed point is reached
+echo "GINO: Inliner: Start"
+noelle-fixedpoint $1 $1 "gino-load" -inliner ${@:2}
+echo "GINO: Inliner: Exit"
diff --git a/src/core/scripts/gino-io b/src/core/scripts/gino-io
--- a/src/core/scripts/gino-io
+++ b/src/core/scripts/gino-io
@@ -1,12 +1,6 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
-bcFile="$@" ;
-
-# Set the command to execute
-cmdToExecute="gino-load -inputoutput ${bcFile} -o ${bcFile}"
-echo $cmdToExecute ;
-
-# Execute the command
-eval $cmdToExecute ;
+# set the command to execute
+gino-load -inputoutput $1 -o $1
diff --git a/src/core/scripts/gino-load b/src/core/scripts/gino-load
--- a/src/core/scripts/gino-load
+++ b/src/core/scripts/gino-load
@@ -1,10 +1,7 @@
 #!/bin/bash -e
 
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
+
 installDir=$(gino-config --prefix)
 
-# Set the command to execute
-cmdToExecute="noelle-load -load ${installDir}/lib/GinoCore.so -load ${installDir}/lib/GinoTools.so ${@}"
-echo $cmdToExecute ;
-
-# Execute
-eval $cmdToExecute ;
+noelle-load -load ${installDir}/lib/GinoCore.so -load ${installDir}/lib/GinoTools.so ${@}
diff --git a/src/core/scripts/gino-planner b/src/core/scripts/gino-planner
--- a/src/core/scripts/gino-planner
+++ b/src/core/scripts/gino-planner
@@ -1,10 +1,5 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
-# Set the command to execute
-cmdToExecute="gino-load -planner ${@}"
-echo $cmdToExecute ;
-
-# Execute
-eval $cmdToExecute ;
+gino-load -planner $@
diff --git a/src/core/scripts/gino-pre b/src/core/scripts/gino-pre
--- a/src/core/scripts/gino-pre
+++ b/src/core/scripts/gino-pre
@@ -1,109 +1,85 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
-# Configurations
-enablePrivatizer="1" ;
-enableEnablers="1" ;
-enableDead="1" ;
+# configurations
+enablePrivatizer="1"
+enableEnablers="1"
+enableDead="1"
 
-# Partition the arguments between options and not
-options="" ;
-notOptions="" ;
+# partition the arguments between options and not
+options=""
+notOptions=""
 for var in "$@" ; do
   if [[ $var == -* ]] ; then
 
-    # Handle custom options
+    # handle custom options
     if [[ $var == "-noelle-disable-privatizer" ]] ; then
-      enablePrivatizer="0" ;
-      continue ;
+      enablePrivatizer="0"
+      continue
     fi
+
     if [[ $var == "-noelle-disable-enablers" ]] ; then
-      enableEnablers="0" ;
-      continue ;
+      enableEnablers="0"
+      continue
     fi
+
     if [[ $var == "-noelle-disable-dead" ]] ; then
-      enableDead="0" ;
-      continue ;
+      enableDead="0"
+      continue
     fi
+
     if [[ $var == -noelle-parallelizer-* ]] ; then
-
-      # Skip all parallelizer-specific options
-      continue ;
+      # skip all parallelizer-specific options
+      continue
     fi
-
-    # General options
-    options="$options $var" ;
-
+    # general options
+    options="$options $var"
   else 
-    notOptions="$notOptions $var" ;
+    notOptions="$notOptions $var"
   fi
 done
 
-# Strip debugging symbols 
-cmdToExecute="opt --strip-debug --strip-debug-declare $notOptions -o $notOptions"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# strip debugging symbols 
+opt --strip-debug --strip-debug-declare $notOptions -o $notOptions
 
-# Delete dead functions
+# delete dead functions
 if test "$enableDead" == "1" ; then
-  cmdToExecute="noelle-deadcode $notOptions $notOptions"
-  echo $cmdToExecute ;
-  eval $cmdToExecute ;
+  noelle-deadcode $notOptions $notOptions
 fi
 
-# Normalize the code
-cmdToExecute="noelle-simplification $notOptions -o $notOptions"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# normalize the code
+noelle-simplification $notOptions -o $notOptions
 
-# Make file accesses more amenable for parallelization
-cmdToExecute="gino-io $notOptions"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# make file accesses more amenable for parallelization
+gino-io $notOptions
 
-# Inline functions
-cmdToExecute="gino-inline $notOptions \"-noelle-inliner-verbose=1 $options\""
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# inline functions
+gino-inline $notOptions "-noelle-inliner-verbose=1 $options"
 
-# Normalize the code
-cmdToExecute="noelle-simplification $notOptions -o $notOptions"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# normalize the code
+noelle-simplification $notOptions -o $notOptions
 
-# Delete dead functions
+# delete dead functions
 if test "$enableDead" == "1" ; then
-  cmdToExecute="noelle-deadcode $notOptions $notOptions"
-  echo $cmdToExecute ;
-  eval $cmdToExecute ;
+  noelle-deadcode $notOptions $notOptions
 fi
 
-# Normalize the code
-cmdToExecute="noelle-simplification $notOptions -o $notOptions"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# normalize the code
+noelle-simplification $notOptions -o $notOptions
 
-# Run the privatizer
+# run the privatizer
 if test "$enablePrivatizer" == "1" ; then
-  cmdToExecute="noelle-privatizer $notOptions $options"
-  echo $cmdToExecute ;
-  eval $cmdToExecute ;
+  noelle-privatizer $notOptions $options
 fi
 
-# Run the enablers
+# run the enablers
 if test "$enableEnablers" == "1" ; then
-  cmdToExecute="gino-enable $notOptions $notOptions $options"
-  echo $cmdToExecute ;
-  eval $cmdToExecute ;
+  gino-enable $notOptions $notOptions $options
 fi
 
-# Normalize the code
-cmdToExecute="noelle-simplification $notOptions -o $notOptions"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# normalize the code
+noelle-simplification $notOptions -o $notOptions
 
-# Clean up the metadata that is no longer valid
-cmdToExecute="noelle-meta-clean $notOptions -o $notOptions"
-echo $cmdToExecute ;
-eval $cmdToExecute ;
+# clean up the metadata that is no longer valid
+noelle-meta-clean $notOptions -o $notOptions
diff --git a/src/tools/scripts/gino-loop-single b/src/tools/scripts/gino-loop-single
--- a/src/tools/scripts/gino-loop-single
+++ b/src/tools/scripts/gino-loop-single
@@ -1,6 +1,6 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
 usage() {
   echo "USAGE: `basename $0` INPUT_BC [OPTIONS]..."
diff --git a/src/tools/scripts/gino-plan-info b/src/tools/scripts/gino-plan-info
--- a/src/tools/scripts/gino-plan-info
+++ b/src/tools/scripts/gino-plan-info
@@ -1,8 +1,7 @@
 #!/bin/bash -e
 
-installDir=$(gino-config --prefix)
+trap 'echo "error: $(basename $0): line $LINENO"; exit 1' ERR
 
-# Check the inputs
 if test $# -lt 1 ; then
   echo "USAGE: `basename $0` IR_FILE [OPTIONS]..."
   echo
@@ -16,6 +15,4 @@ if test $# -lt 1 ; then
   exit 1
 fi
 
-cmdToExecute="gino-load -noelle-verbose=0 -ParallelizerPlanInfo -disable-output $@" 
-echo $cmdToExecute
-eval $cmdToExecute 
+gino-load -noelle-verbose=0 -ParallelizerPlanInfo -disable-output $@
